aws:
  region: eu-central-1
  zoneType: public
  #roleArn: "arn:aws:iam::261033416540:role/external-dns"
domainFilters:
  - harut.velvioo.brainscale.cloud
  
provider: aws
logLevel: info

sources:
  - service
  - ingress

policy: sync

registry: txt

txtOwnerId: velvioo

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::261033416540:role/external-dns 
