# values.yaml
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::548844171305:role/AccessSecretsMannagerRole

secretStores:
  - apiVersion: external-secrets.io/v1alpha1
    kind: SecretStore
    metadata:
      name: aws-secrets-manager
      namespace: external-secrets
    spec:
      provider:
        aws:
          service: SecretsManager
          region: eu-cental-1
          auth:
            jwt:
              serviceAccountRef:
                name: external-secrets-sa

externalSecrets:
  - apiVersion: external-secrets.io/v1alpha1
    kind: ExternalSecret
    metadata:
      name: my-secret
      namespace: external-secrets
    spec:
      refreshInterval: 1h
      secretStoreRef:
        name: aws-secrets-manager
        kind: SecretStore
      target:
        name: my-k8s-secret
        creationPolicy: Owner
      data:
        - secretKey: db-username
          remoteRef:
            key: rds!db-3c60b61f-7387-4483-8795-1eb923b69fd2
            property: username
        - secretKey: db-password
          remoteRef:
            key: rds!db-3c60b61f-7387-4483-8795-1eb923b69fd2
            property: password
