aws:
  region: eu-central-1
domainFilters:
  - harut.velvioo.brainscale.cloud
  
provider: aws
logLevel: info

sources:
  - service
  - ingress

policy: sync

registry: txt
# R53Zone ID
txtOwnerId: velvio

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::261033416540:role/external-dns 
