apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager-issuers
    server: https://kubernetes.default.svc
  sources:
  - repoURL: https://charts.adfinis.com
    chart: cert-manager-issuers
    targetRevision: 0.2.5
    helm:
      valueFiles:
      - $values/Chart-test/values/cert-manager-issuer-values.yaml
  - repoURL: https://github.com/elbakya/argocd_application.git
    targetRevision: main
    ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
