apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager-issuers
    server: https://kubernetes.default.svc
  source:
    repoURL: https://artifacthub.io/packages/helm/adfinis/cert-manager-issuers
    chart: cert-manager-issuers
    targetRevision: 0.2.5
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
