apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    chart: external-dns
    targetRevision: 6.35.0
    helm:
      valueFiles:
      - $values/Chart-test/values/external-dns-values.yaml
  - repoURL: https://github.com/elbakya/argocd_application.git
    targetRevision: main
    ref: values
    #helm:
    #  parameters:
    #  - name: "aws.region"
    #    value: eu-central-1
    #  - name: "domainFilters"
    #    value: harut.velvioo.brainscale.cloud
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
