apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hotel-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: hotel-app
    server: https://kubernetes.default.svc
  sources:
  - repoURL: 'https://github.com/elbakya/hotel-app-helm-chart'
    path: .
    targetRevision: HEAD
    helm:
      valueFiles:
      - $values/Chart-test/values/test-value.yaml
  - repoURL: https://github.com/elbakya/argocd_application.git
    targetRevision: main
    ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  parameters:
    - name: rdsHost
      value: "testtest"
