apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hotel-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: hotel-app
    server: https://kubernetes.default.svc
  source:
  - repoURL: https://github.com/elbakya.git
    targetRevision: master
    path: hotel-app-helm-chart
    helm:
      releaseName: hotel-app-helm-chart
      valueFiles:
      - values.yaml
    #repoURL: https://github.com/elbakya
    #chart: hotel-app-helm-chart
    #targetRevision: '2.0'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
