apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: mysql
    server: https://kubernetes.default.svc
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    chart: mysql
    targetRevision: 10.2.4
    helm:
      valueFiles:
      - $values/Chart-test/values/mysql-values.yaml
  - repoURL: https://github.com/elbakya/argocd_application.git
    targetRevision: main
    ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
