helm:
  parameters:
  - name: ports.container_port
    value: "3000"
    forcestring: false
  - name: ports.lb_port
    value: "80"
    forcestring: false
  - name: host
    value: kub.am
    forcestring: false
  - name: replicaCount
    value: "3"
    forcestring: false
  - name: containers.image
    value: public.ecr.aws/s1e9p4h4/brainscale-task2
    forcestring: true
  - name: containers.tag
    value: latest
    forcestring: true
